version: "3.3"

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_HOST_AUTH_METHOD
    ports:
      - 5431:5432
    volumes:
      - pg-data:/var/lib/postgresql/data

  backend:
    depends_on:
      - db
    image: starterkit/project:latest
    build:
      context: ./
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - DB_HOST
      - DB_PORT
    ports:
      - 8080:8080

volumes:
  pg-data:
