# starterkit/dependencies:latest
FROM ubuntu:bionic

RUN apt-get update && apt-get install -y curl libghc-postgresql-libpq-dev
RUN curl -sSL https://get.haskellstack.org/ | sh
RUN stack update

COPY ./ haskell-starter-kit/

WORKDIR /haskell-starter-kit/
RUN stack setup
RUN stack build --only-dependencies
