name:                haskell-starter-kit
version:             0.1.0.0
github:              "githubuser/haskell-starter-kit"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskell-starter-kit#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- bytestring
- text
- time
- typerep-map

# Logger
- co-log

# Serializing
- aeson

default-extensions:
- RecordWildCards
- OverloadedStrings
- FlexibleContexts
- FlexibleInstances
- StandaloneDeriving
- ScopedTypeVariables
- ExplicitForAll

library:
  source-dirs: src
  dependencies:
    - time
    - mtl
    - unliftio-core
    - unliftio
    - safe-exceptions
    - configurator
    - resourcet
    - monad-logger
    - resource-pool
    - postgresql-simple
    - persistent
    - persistent-postgresql
    - persistent-template
    - esqueleto

executables:
  haskell-starter-kit-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-starter-kit
    when: # workaround from https://github.com/sol/hpack/issues/303
    - condition: false
      other-modules: Paths_haskell_starter_kit

tests:
  haskell-starter-kit-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-starter-kit
    when: # workaround from https://github.com/sol/hpack/issues/303
    - condition: false
      other-modules: Paths_haskell_starter_kit
