name:                haskell-starter-kit
version:             0.1.0.0
github:              "githubuser/haskell-starter-kit"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskell-starter-kit#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- bytestring
- text
- containers
- time
- unliftio-core
- unliftio
- safe-exceptions
- typerep-map
- random
- random-shuffle
- stm
- directory
- cryptonite
- memory
- basement

- configurator
- resourcet
- resource-pool

# Logger
- co-log
- monad-logger

# Database
- postgresql-simple
- persistent
- persistent-postgresql
- persistent-template
- esqueleto

# Web
- aeson
- jose
- http-client
- http-client-tls
- wai
- warp
- wai-logger
- wai-cors
- servant-client
- servant-options
- servant-server
- servant-auth
- servant-auth-server
- servant-foreign

ghc-options:
- -Wall
- -Werror=missing-fields
- -Werror=incomplete-record-updates
- -Werror=missing-methods
- -Werror=incomplete-patterns

default-extensions:
- RecordWildCards
- OverloadedStrings
- FlexibleContexts
- FlexibleInstances
- StandaloneDeriving
- ScopedTypeVariables
- ExplicitForAll
- TypeOperators
- DeriveGeneric
- MonoLocalBinds

library:
  source-dirs: src


executables:
  haskell-starter-kit-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-starter-kit
    when: # workaround from https://github.com/sol/hpack/issues/303
    - condition: false
      other-modules: Paths_haskell_starter_kit

tests:
  haskell-starter-kit-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-starter-kit

    - hspec
    - hspec-core
    - hspec-wai
    - tasty
    - tasty-hspec

    # extra
    - http-types
    - wai-extra
    when: # workaround from https://github.com/sol/hpack/issues/303
    - condition: false
      other-modules: Paths_haskell_starter_kit
