#!/bin/sh

set -e

ORMOLU_VERSION=0.1.4.1
ORMOLU_OPTIONS="--mode inplace --check-idempotence"

ROOT=$(git rev-parse --show-toplevel)
cd "$ROOT"

FMT=$(stack exec --package ormolu-"$ORMOLU_VERSION" which ormolu)
find . \( -path ./stack-work -o -path ./.git \) -prune \
       -o -type f -name \*.hs \
       -exec "$FMT" $ORMOLU_OPTIONS '{}' +

